### ISSUE TITLE
[feature-request] improved sample-loading and viewing

### ISSUE THREAD

**Issue by rhetr** [openAVproductions/openAV-Fabla#18]
Often I have to go through multiple samplepacks to find the sample I want. fabla's current design isn't entirely conducive to this. I think it'd be a great improvement if fabla had a file-browser on the left similar to carla's with 1)the ability to set bookmarks 2)the ability to playback samples upon being selected (by mouse or by arrow keys). This would also mean samples would most likely be drag-droppable, which is also helpful and more efficient than right-clicking all the time.

(I think a long-term solution to this issue would be another dedicated filebrowsing app specifically for linux audio applications (mainly with realtime sample viewing and a small window size), which could be used with both carla and fabla.)

**Comment by georgkrause** [comment]
@harryhaaren how about this issue? I could move it to Fabla2 but since it has an new way to handle samples, it may be not implemented there. so just close it?

**Comment by naught101** [comment]
https://github.com/openAVproductions/openAV-Fabla2/issues/6
