### ISSUE TITLE
Configurable MIDI Base Note

### ISSUE THREAD

**Issue by harryhaaren** [openAVproductions/openAV-Fabla#46]
As per FB message, a user wishes to be able to configure the "base note" of Fabla - that instead of note 36 as the lowest, a different note can be used in order to easily control Fabla with a LPD8 controller which is mapped from C4 (note 60).

**Comment by georgkrause** [comment]
@harryhaaren i looked into the code, am i right only this line of code needs a change for setting the base note? https://github.com/openAVproductions/openAV-Fabla/blob/cfbd4b36165f1708b885610fa32775f75997579a/gui/fabla_ui.cxx#L195

**Comment by harryhaaren** [comment]
That's the base note yep, there is another for note-off: https://github.com/openAVproductions/openAV-Fabla/blob/cfbd4b36165f1708b885610fa32775f75997579a/gui/fabla_ui.cxx#L239

The "issue" is how do we actually control this - without breaking backwards compatibility. Adding an Atom message to set the base-note, and allowing the UI to send that Atom message is probably the best way.

**Comment by georgkrause** [comment]
alright. this time i dont have time to go into code, but maybe i can try something next week (since the luppp gui changes for more tracks/scenes is driving me crazy)

**Comment by georgkrause** [comment]
@harryhaaren since you said Fabla 1 wont become new features, i would like to move this to Fabla 2. Is it okay?

**Comment by harryhaaren** [comment]
I'll just close as won't-fix.
