### ISSUE TITLE
Crash Overwriting playing sample

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Fabla#47]
I loaded a pretty long sample into Fabla in jalv. I hit it and while it played, i tried to load another sample in the slot. Fabla crashes.

`[1]    17435 segmentation fault (core dumped)  jalv.gtk http://www.openavproductions.com/fabla`

While starting it tells me:

`Cannot lock down 82274202 byte memory area (Nicht genügend Hauptspeicher verfügbar)`

**Comment by harryhaaren** [comment]
Thanks for reporting, please test to verify fix is working.
