### ISSUE TITLE
Integrate a nicer File Selection Dialog

### ISSUE THREAD

**Issue by unfa** [openAVproductions/openAV-Fabla#48]
Typing and pasting filenames, paths, etc would be nice :)

The system bookmarks work, but need to be activated - the dialog seems a bit minimalistic.

**Comment by harryhaaren** [comment]
The current file dialog is implemented in NTK. It is not easy / feasible to implement small features for it - so this is unlikely to happen. What about using the Fabla2 type file browser https://github.com/x42/sofd ? Would that be better?

**Comment by harryhaaren** [comment]
Closing as unlikely to implement new/improve features.
