### ISSUE TITLE
Fabla GUI does not show details for all pads

### ISSUE THREAD

**Issue by schnitzeltony** [openAVproductions/openAV-Fabla#49]
I use fabla within qtractor. After selection of preset (e.g fabla808 - that has samples for all pads) and opening the GUI not all Pads display Number/Sample:
![fabla808](https://user-images.githubusercontent.com/2571823/40857409-5f4e022a-65db-11e8-97b7-8450d297e891.png)

This behaviour is same for
* Openembedded build from latest master
* Fedora Package shipped

**Comment by harryhaaren** [comment]
Hi @schnitzeltony, I've got an older machine, QTractor 0.7.1, Fabla shows up all the pads fine... so I can't reproduce. What version of QTractor are you using, and what version of the "Suil" library?

**Comment by schnitzeltony** [comment]
Ahh - I forgot this completely - sorry.

My versions:
qtractor 0.9.1
suil: 0.10.0

Some further notes:
* With ardour 5.12 there is no such issue
* At the time of reporting I was using Qt stable 5.9.x. I remember there were very strange issues with qtractor(splitters in qtractor improperly sized / contents not drawn properly / native dialogs replaced by Qt dialogs...) after update Qt 5.9.4 -> 5.9.5. When I saw that Qt 5.9.6 did not fix, I moved to Qt5.11 and all qtractor issues are gone. Don't remember which Qt version I was using when opening this issue.
Long talk: Will try fabla on qtractor with Qt 5.11 and report (may last - you caught me in the middle of massive image rebuild). Let's hope we can close this then...

**Comment by harryhaaren** [comment]
Thanks for the update - if this doesn't work, its nothing to do with Fabla - it is to do with the QT version and SUIL library... unfortunatly embedded UIs are complex, and the issues you're having is caused by this complexity. Regardless, there is nothing Fabla code can do about it..

Please do test latest when you're set up with it - and if an issue persists we can file an issue against QTractor and/or SUIL.

**Comment by harryhaaren** [comment]
Cannot reproduce, please re-open with repro details if this is still and issue.
