### ISSUE TITLE
High DPI support

### ISSUE THREAD

**Issue by cmt227** [openAVproductions/openAV-Fabla#50]
Hi,

Are there any plans to implement high DPI support in the GUI?

I really like Fabla but it's hard to use when the GUI appears very small. I assume this may come down to NTK supporting this feature.

Thanks.

**Comment by harryhaaren** [comment]
Hi @cmt227,

Correct that NTK would have to support it. Currently I don't know of any HighDPI plans for NTK - sorry.
I should note that new OpenAV UI's for plugins are being built using [AVTKA](https://github.com/openAVproductions/openAV-Avtka), which *does* support HighDPI.. although we use a sneaky method to do so.. ;)

If you're comfortable with compiling software, please do check the AVTKA demo app, and check if that is usable from a HighDPI point-of-view? I don't have a HighDPI screen to actually test on - but I think it should be readable regardless of DPI settings, as the UI supports scaling in a "high-dpi" sense (lines get fatter, text gets bigger, etc)

Assuming AVTKA is a workable solution, I think it would be a few days work to build an AVTKA based Fabla UI - which if you catch me in a good mood might just happen - no promises though, the sun is shining here in Ireland so I'm tempted to go outside :D Cheers, -Harry

**Comment by harryhaaren** [comment]
Closing this - not expecting to do more than basic maintainership of Fabla.
