### ISSUE TITLE
Compile question

### ISSUE THREAD

**Issue by axdre** [openAVproductions/openAV-Fabla#55]
Hi

My details 4.15.0-46-lowlatency - Ubuntu = VERSION="18.04.2 LTS (Bionic Beaver)

$ cmake /usr/lib/lv2/openAV-Fabla-master/
CMake Error: The source "/usr/lib/lv2/openAV-Fabla-master/CMakeLists.txt" does not match the source "/usr/lib/lv2/openAV-Fabla-master/build/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.

Any Idea what's happening here...

**Comment by axdre** [comment]
I'm also getting this cmake error:

$ cmake /usr/lib/lv2/openAV-Fabla-master
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:470 (message):
  pkg-config tool not found
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:18 (pkg_check_modules)


CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:470 (message):
  pkg-config tool not found
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:21 (pkg_check_modules)


CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:470 (message):
  pkg-config tool not found
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:25 (pkg_check_modules)



  Fabla Configuration : 1.3.2
-----------------------
* Install Directory               : /usr/local

-- Configuring incomplete, errors occurred!
See also "/usr/lib/lv2/openAV-Fabla-master/CMakeFiles/CMakeOutput.log".

**Comment by trebmuh** [comment]
` -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)`

You want to install pkg-config.

**Comment by axdre** [comment]
Ok now i got a configure error trying to install pkg-config:

configure: error: Either a previously installed pkg-config or "glib-2.0 >= 2.16" could not be found. Please set GLIB_CFLAGS and GLIB_LIBS to the correct values or pass --with-internal-glib to configure to use the bundled copy.


I have no idea how to fix this...

**Comment by trebmuh** [comment]
It does tell you that you're missing the development libr for glib-2.0

@axdre : if you don't know how to fix this, you might be better to use a distribution package I guess. What distribution are you using?

**Comment by trebmuh** [comment]
Mmmm well, strike that. What do you mean by "Ok now i got a configure error trying to install pkg-config:" ? How did you tru to install pkg-config?

Still : What distribution are you using?

**Comment by axdre** [comment]
Here is my distribution:
Linux version 4.15.0-46-lowlatency (buildd@lgw01-amd64-038) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #49-Ubuntu SMP PREEMPT Wed Feb 6 10:23:17 UTC 2019 (Ubuntu 4.15.0-46.49-lowlatency 4.15.18)

Here is the address I downloaded pkg-config:
$ wget http://pkgconfig.freedesktop.org/releases/pkg-config-0.28.tar.gz

**Comment by axdre** [comment]
Now I'm getting this message when running  cmake:
$ cmake /usr/lib/lv2/openAV-Fabla-master
-- Checking for module 'ntk'
--   No package 'ntk' found
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:21 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/usr/lib/lv2/openAV-Fabla-master/CMakeFiles/CMakeOutput.log".

Then I when on trying to install this "ntk", here is what I got so far:
~/ntk$ ./waf configure --prefix=/usr
Setting top to                           : /home/costa/ntk 
Setting out to                           : /home/costa/ntk/build 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for program 'pkg-config'                    : /usr/bin/pkg-config 
Checking for 'x11'                                   : not found 
The configuration failed
(complete log in /home/costa/ntk/build/config.log)

**Comment by axdre** [comment]
x11 not found....

**Comment by trebmuh** [comment]
If you're using ubuntu, then you shouldn't have to compile pkg-config yourself. Just install it with your usual package manager (synaptic, apt-get,...).

Look at the KXstudio projet which should provide you Fabla, without the burden to compile it yourself.

**Comment by axdre** [comment]
I didn't know it was possible. The README txt should inform that for people like me....
Thanks though!

**Comment by trebmuh** [comment]
> The README txt should inform that for people like me....

If every program should put something like that in their README file, it would be a nightmare to do, and to maintain over time. I'd say that's more about you starting to get the ropes of a new world. Welcome!

**Comment by harryhaaren** [comment]
Thanks for opening an issue here Axdre, and thanks Trebmuh for providing answers! Just for future readers, the easiest way to install OpenAV software is usually by package managers, which depends on your distro; Many popular distros are based on Debian/Ubuntu, and the KXStudio repos are probably the best place to get the software. See more details here: http://openavproductions.com/install/

**Comment by harryhaaren** [comment]
Closing as this seems to be resolved.
