### ISSUE TITLE
dsp/fabla.cxx:150:mismatched allocation function

### ISSUE THREAD

**Issue by dcb314** [openAVproductions/openAV-Fabla#65]
dsp/fabla.cxx:150:9: warning: 'void free(void*)' called on pointer returned from a mismatched allocation function [-Wmismatched-new-delete]

Source code is

  Sample* sample = new Sample();
  SF_INFO* const info    = &sample->info;
  SNDFILE* const sndfile = sf_open(path, SFM_READ, info);

  if (!sndfile) // || !info->frames ) { // || (info->channels != 1)) {
  {
    lv2_log_error(&self->logger, "Failed to open sample '%s'\n", path);
    free(sample);

**Comment by sjaehn** [comment]
Should be easy to fix for @harryhaaren by using `delete` instead of `free`, I guess.
