### ISSUE TITLE
Building on arm64

### ISSUE THREAD

**Issue by mntmn** [openAVproductions/openAV-Fabla#67]
To be able to build fabla on arm/arm64 I had to remove the `-msse2` and `-mfpmath=sse` from `CMakeLists.txt`:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index b48fb68..8eff050 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -32,8 +32,8 @@ SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -Wall -O3 -Wno-unused-variable -fvisi
 
 IF(BUILD_SSE)
   IF(NOT ${CMAKE_SYSTEM_PROCESSOR} MATCHES "arm")
-    SET(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS} -msse2 -mfpmath=sse -ffast-math")
-    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -msse2 -mfpmath=sse -ffast-math -Wno-trigraphs")
+    SET(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS} -ffast-math")
+    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -ffast-math -Wno-trigraphs")
   ENDIF()
 ENDIF()
```

After that, it builds and works absolutely fine.

**Comment by harryhaaren** [comment]
There's a CMake option[1] to disable SSE, just set it to `OFF` before running `cmake ..` in your build directory, then no SSE math will be used. Will mark as closed as there is a known and proper solution to this already.

[1] https://github.com/openAVproductions/openAV-Fabla/blob/master/CMakeLists.txt#L10
