### ISSUE TITLE
SSE build not disabled on aarch64

### ISSUE THREAD

**Issue by hfiguiere** [openAVproductions/openAV-Fabla#70]
The following logic in `CMakeList.txt` doesn't work on aarch64
```
IF(BUILD_SSE)
  IF(NOT ${CMAKE_SYSTEM_PROCESSOR} MATCHES "arm")
    SET(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS} -msse2 -mfpmath=sse -ffast-math")
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -msse2 -mfpmath=sse -ffast-math -Wno-trigraphs")
  ENDIF()
ENDIF()
```

This is because `CMAKE_SYSTEM_PROCESSOR` is the output of `uname -m` which would be `aarch64`. Ideally the better logic would be to opt in the build with SSE only on the intel architectures.

Also, as an aside, `-ffast-math` should be avoided as it has side effects at runtime.

**Comment by harryhaaren** [comment]
Removed those build flags in above commit, closing.
