### ISSUE TITLE
Do not use `-ffast-math`

### ISSUE THREAD

**Issue by hfiguiere** [openAVproductions/openAV-Fabla#71]
Fabla build / link with `-ffast-math` which has a runtime side effect.

More details (among other sources):

https://bugzilla.redhat.com/show_bug.cgi?id=1127544
https://simonbyrne.github.io/notes/fastmath/

This is especially a problem since this is a plugin.

**Comment by harryhaaren** [comment]
Removed `-ffast-math` build flags in above commit, closing.
