### ISSUE TITLE
ntk

### ISSUE THREAD

**Issue by folkertvanheusden** [openAVproductions/openAV-Fabla#72]
Hi,

Both repos from the README for ntk are giving error 500 and thus cannot be cloned.

**Comment by dromer** [comment]
I think you already found it here: https://github.com/linuxaudio/ntk ;)

**Comment by harryhaaren** [comment]
Thanks for reporting @folkertvanheusden , and @dromer  for providing another link, added to the README. I'm on holidays, so apologies for lack of any response till now!
